# Generated by Django 3.1.4 on 2021-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('disease_id', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500, null=True)),
                ('class_of', models.CharField(max_length=500, null=True)),
                ('semantic_type', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metabolity',
            fields=[
                ('metabolity_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('compartment', models.CharField(max_length=500, null=True)),
                ('notes', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('notes', models.JSONField(null=True)),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('gene_reaction_rule', models.CharField(max_length=500)),
                ('metabolities', models.ManyToManyField(to='articles.Metabolity')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_text', models.CharField(max_length=5000, null=True)),
                ('pub_date', models.DateField()),
                ('name', models.CharField(max_length=500)),
                ('doi', models.CharField(max_length=500, null=True)),
                ('tagged', models.JSONField(null=True)),
                ('authors', models.ManyToManyField(to='articles.Author')),
                ('metabolities', models.ManyToManyField(to='articles.Metabolity')),
            ],
        ),
    ]
