# Generated by Django 3.1.4 on 2020-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metabolity',
            fields=[
                ('metabolity_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('compartment', models.CharField(max_length=500, null=True)),
                ('notes', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_text', models.CharField(max_length=2500, null=True)),
                ('pub_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200, null=True)),
                ('authors', models.ManyToManyField(to='articles.Author')),
            ],
        ),
    ]
