# Generated by Django 3.1.4 on 2021-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tagged',
        ),
        migrations.AddField(
            model_name='article',
            name='diseases',
            field=models.ManyToManyField(to='articles.Disease'),
        ),
    ]
