# Generated by Django 3.1.4 on 2020-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201230_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract_text',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
