# Generated by Django 3.1.4 on 2021-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201230_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='metabolities',
            field=models.ManyToManyField(to='articles.Metabolity'),
        ),
    ]
