# Generated by Django 3.1.4 on 2021-02-09 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathway',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
