# Generated by Django 3.1.4 on 2021-01-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_metabolities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('notes', models.JSONField(null=True)),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('gene_reaction_rule', models.CharField(max_length=500)),
                ('metabolities', models.ManyToManyField(to='articles.Metabolity')),
            ],
        ),
    ]
