# Generated by Django 3.1.4 on 2021-01-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagged',
            field=models.JSONField(null=True),
        ),
    ]
