# Generated by Django 3.1.4 on 2021-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_pathways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract_text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
