# Generated by Django 3.1.4 on 2021-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210329_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract_text',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
