# Generated by Django 3.1.4 on 2021-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210329_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(db_index=True, to='articles.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='diseases',
            field=models.ManyToManyField(db_index=True, to='articles.Disease'),
        ),
        migrations.AlterField(
            model_name='article',
            name='metabolities',
            field=models.ManyToManyField(db_index=True, to='articles.Metabolity'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pathways',
            field=models.ManyToManyField(db_index=True, to='articles.Pathway'),
        ),
    ]
