# Generated by Django 3.1.4 on 2021-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210329_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract_text',
            field=models.CharField(db_index=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
