# Generated by Django 3.1.4 on 2021-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210606_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_id',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metabolity',
            name='metabolity_id',
            field=models.CharField(db_index=True, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='id',
            field=models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='metabolities',
            field=models.ManyToManyField(db_index=True, to='articles.Metabolity'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_id',
            field=models.CharField(db_index=True, max_length=500, primary_key=True, serialize=False),
        ),
    ]
