# Generated by Django 4.0.dev20210524143312 on 2021-06-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210606_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False),
        ),
    ]
