# Generated by Django 4.0.dev20210524143312 on 2021-06-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
