# Generated by Django 4.0.dev20210616072752 on 2021-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayDiseaseRelation',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('pathway_name', models.CharField(db_index=True, max_length=500)),
                ('disease_name', models.CharField(db_index=True, max_length=500)),
                ('article_id', models.IntegerField(blank=True, null=True)),
                ('sia_score', models.CharField(max_length=200, null=True)),
                ('textblob_score', models.CharField(max_length=200, null=True)),
                ('flair_score', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'pathway_disease_relation',
                'ordering': ['pathway_name'],
            },
        ),
        migrations.AddIndex(
            model_name='pathwaydiseaserelation',
            index=models.Index(fields=['pathway_name', 'disease_name'], name='pathway_dis_pathway_9b1475_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pathwaydiseaserelation',
            unique_together={('pathway_name', 'disease_name')},
        ),
        migrations.AlterIndexTogether(
            name='pathwaydiseaserelation',
            index_together={('pathway_name', 'disease_name')},
        ),
    ]
