# Generated by Django 4.0.dev20210616072752 on 2021-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_pathwaydiseaserelation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pathwaydiseaserelation',
            name='pathway_dis_pathway_9b1475_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pathwaydiseaserelation',
            unique_together={('pathway_name', 'disease_name', 'article_id')},
        ),
        migrations.AlterIndexTogether(
            name='pathwaydiseaserelation',
            index_together={('pathway_name', 'disease_name', 'article_id')},
        ),
        migrations.AddIndex(
            model_name='pathwaydiseaserelation',
            index=models.Index(fields=['pathway_name', 'disease_name', 'article_id'], name='pathway_dis_pathway_8a0a63_idx'),
        ),
    ]
