# Generated by Django 4.0.dev20210616072752 on 2021-06-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_pathwaydiseaserelation_pathway_dis_pathway_9b1475_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathwaydiseaserelation',
            name='textblob_score',
        ),
        migrations.AddField(
            model_name='pathwaydiseaserelation',
            name='textblob_polarity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pathwaydiseaserelation',
            name='textblob_subjectivity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pathwaydiseaserelation',
            name='flair_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pathwaydiseaserelation',
            name='sia_score',
            field=models.FloatField(null=True),
        ),
    ]
