# Generated by Django 4.0.dev20210616072752 on 2021-06-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_remove_pathwaydiseaserelation_pathway_dis_pathway_8a0a63_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaydiseaserelation',
            name='sentence',
            field=models.CharField(db_index=True, max_length=5000, null=True),
        ),
    ]
